# Generated by Django 5.0 on 2024-08-28 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('elector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='electors',
            field=models.ManyToManyField(blank=True, related_name='elections', to='elector.elector'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='administration.election'),
        ),
        migrations.AddField(
            model_name='vote',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='administration.election'),
        ),
    ]
